### ISSUE TITLE
Adopt an official color scheme

### ISSUE THREAD

**Issue by BernardZhao** [ocf/ocfstatic#115]
Currently the site uses an arbitrary pink color that I chose, but the primary and second colors etc. should all be set to the SASS variables we want at `src/assets/styles.scss`. A good starting point for this is probably the old website redesign files that opstaff generated for us, which can be found [here](https://drive.google.com/file/d/10O8aZy1JmZGWoVYMdN32aZ-hhOwayyPz/view?usp=sharing). I think that bulma's default grays do a good job already, so it's really the main colors we have to pick.

**Comment by nikhiljha** [comment]
We should also make sure that the colors picked meet the WCAG AAA guidelines for small text.

Website to test: https://webaim.org/resources/contrastchecker/

**Comment by expedited** [comment]
Do we have any source of truth for a style guide at the OCF? I think this would be a good time to review this because I think the ultimate goal should be to maintain consistency in fonts, colors, and design principles across the website, event banners, lab posters

**Comment by BernardZhao** [comment]
Best we have is linked above, but we should also wait until I move this repo under ocf so that other people get notified about our discussion.

**Comment by expedited** [comment]
Sounds like this should be backlogged until we have a solid solution to unify all design in the org, and then we can figure out how we should organize the site to match the design standard.
