### ISSUE TITLE
Add account creation functionality

### ISSUE THREAD

**Issue by BernardZhao** [ocf/ocfstatic#116]
Goes hand in hand with #118.

**Comment by RonitNath** [comment]
@Kalissaac we need to implement a few more api endpoints for this, probably, unless theyre already there. These mainly: https://github.com/ocf/ocfweb/blob/6c9a70b35be8848808df4ab0bb5eae1c3c4c6cce/ocfweb/account/urls.py
Do you think we could roll those into the api updates you're doing? I'm not sure what state your code's at.

**Comment by Kalissaac** [comment]
I thought we were sticking with the existing `ocfweb` api and then just throwing ocfstatic in the frontend for that?

If we are instead going with making the new api then yeah I can definitely implement these endpoints as well.

**Comment by RonitNath** [comment]
If we have the existing API and we can reliably access these endpoints,
then no problem we'll just do that.

**Comment by Kalissaac** [comment]
Ok it looks like the current account creation endpoints are pretty tied in with the current ocfweb frontend. I can refactor it into API endpoints, I just need someone to help make sure there's no security issues with the implementation.

**Comment by Kalissaac** [comment]
On the API side this is ready to go here: https://api.ocf.berkeley.edu/docs#/account/register_account_account_register_post

We just need to create a frontend for it
