### ISSUE TITLE
Add About page

### ISSUE THREAD

**Issue by BernardZhao** [ocf/ocfstatic#121]
Not to be confused with the about doc, this page is meant to be an updated version of [this](https://www.ocf.berkeley.edu/about/staff). This involves adding content to `src/pages/About.vue`. I have ideas of lots of cool stuff we could put on here, including an OCF History timeline, etc. This should just be as cool of a page as possible, as it describes why new staff should join!

**Comment by bentref** [comment]
Would this be a good issue for me to work on? I can definitely work on adding content to this but since I'm not super familiar with the OCF I would need some guidance

**Comment by BernardZhao** [comment]
@bentref This would definitely be a good issue for you to tackle, since its pretty self contained and you can try building out whatever you want! The only thing that you might find challenging is thinking of good content to add, but you can probably ask on Slack or something and people will probably have good ideas.

**Comment by jyxzhang** [comment]
I'm thinking of working on porting https://www.ocf.berkeley.edu/docs/about/officers/ to the new website. I haven't looked through everything @bentref has done on the about page so far, but I'm thinking that the "about" on the navbar could be changed to a dropdown, with "What we do", "Officers", and "Timeline" (So far, more content can be added).
