### ISSUE TITLE
Dynamically fetch staff hours

### ISSUE THREAD

**Issue by BernardZhao** [ocf/ocfstatic#125]
Currently the staff hours calendar is a placeholder.

Staff hours are configured in `ocf/etc/configs/staff_hours.yaml`. If we're keeping that same implementation, fetch them from there. On old website, it seems to take a while to update the staff hours--can we improve this?

**Comment by Kalissaac** [comment]
API endpoints now exists here: https://api.ocf.berkeley.edu/docs#/misc/get_staff_hours_staff_hours_get
