### ISSUE TITLE
Add Checklist to Join Staff

### ISSUE THREAD

**Issue by bjb568** [ocf/ocfstatic#160]
[Checklist google doc.](https://docs.google.com/document/d/1tt69LoaQJHBuqtFbaQgP8CgsWnP6r7HDqoNEJRUfUAw/edit?usp=sharing)

I envision this looking like a custom HTML page with a checklist that persists the checked state in localStorage and presents each item as `<details>`/`<summary>`. The details can be copied from the existing https://ocf.io/getinvolved

**Comment by BernardZhao** [comment]
Really like this idea!
