### ISSUE TITLE
Syntax highlighting class names conflict

### ISSUE THREAD

**Issue by bjb568** [ocf/ocfstatic#169]
https://new.ocf.berkeley.edu/docs/services/web/wordpress/

This HTML `<span class="token number">1</span>` renders weird because the `number` class has some style that's intended for something that is not the product of syntax highlighting. That makes it look like this:

<img width="672" alt="Screenshot 2020-09-20 at 19 00 48" src="https://user-images.githubusercontent.com/5396448/93724276-9f42fe00-fb73-11ea-9d72-bcc468ab0da7.png">

Instead of this:

<img width="675" alt="Screenshot 2020-09-20 at 19 00 38" src="https://user-images.githubusercontent.com/5396448/93724282-a833cf80-fb73-11ea-91de-fd4f1a8b1352.png">

**Comment by BernardZhao** [comment]
Yup, I identified this issue with @bentref earlier this week. The global bulma classes are interfering with the classes meant for syntax highlighting, so I think that I need to find a way to isolate these two, or even just not import those bulma classes globally.

**Comment by bentref** [comment]
@BernardZhao Should we close this or is there still work to be done on it? As I recall you managed to fix it with some extra (hacky?) code but you were also going to do a PR to fix the bug in Bulma. How did that go?

**Comment by BernardZhao** [comment]
> 
> 
> @BernardZhao Should we close this or is there still work to be done on it? As I recall you managed to fix it with some extra (hacky?) code but you were also going to do a PR to fix the bug in Bulma. How did that go?

Thanks, I totally forgot to close this. This got fixed in f21995cbb1ea82eb7c74f628f36b889b05e2e0db, thanks for following up
