### ISSUE TITLE
Un-rendered template stuff on /docs/internal/staff/

### ISSUE THREAD

**Issue by bentref** [ocf/ocfstatic#172]
The second line on this page is 

> [[!meta template="docs/staff_index.html"]]

I'm fairly sure that's not supposed to be there; something is probably supposed to be rendered in its place but it's not happening.

**Comment by PotatoParser** [comment]
Looks like the docs were copied from ocfweb. Looks like this page didn't get converted yet. Source: https://github.com/ocf/ocfweb/blob/master/ocfweb/docs/markdown_based.py

**Comment by BernardZhao** [comment]
Yup I totally missed this, but the old docs have a bunch of quirks that are unique to them and most of them I ended up converting by hand. If you see something like this, I must have missed it in the conversion process.

**Comment by BernardZhao** [comment]
Feel free to just go ahead and fix this if you want btw, you can look at how other internal links are done in other docs.

**Comment by bentref** [comment]
@BernardZhao Yeah, this seems like a good thing for me to fix, I'll do it!
