### ISSUE TITLE
Dark Mode Support 

### ISSUE THREAD

**Issue by BernardZhao** [ocf/ocfstatic#174]
Since Bulma 0.9 new light and dark mode helpers have been added, so adding Dark Mode Support should be possible. I think the best way to do it would probably be to see how an existing site implements it, but I would guess that it should mainly be switching between CSS/SASS variables

**Comment by RonitNath** [comment]
I've seen some html templates do it with having a button on the header that switches everything, I'll try to find the example if I can, but that's the jist.

**Comment by bjb568** [comment]
this is how you'd do it with CSS. https://jsfiddle.net/vwe2ju74/
