### ISSUE TITLE
Documentation: Allow to expand a tree in sidebar without going to that page

### ISSUE THREAD

**Issue by bentref** [ocf/ocfstatic#182]
The documentation in the sidebar is organized in a tree structure, such that you have to click on one category to expand it and view the pages contained within it. Currently, clicking on a category such as Tips and Tricks takes the web browser to the page for that category, which isn't a very useful page. But, taking the web browser to that page resets the scroll, so now you have to scroll all the way down to it again to go to one of the pages contained within that category.

Perhaps we could set it up so that clicking the arrow on the right side of the category expands it, but doesn't actually go to that page? Then you can immediately select the item you actually want to go to.

**Comment by BernardZhao** [comment]
Yup, this is a really good idea. I'll see what I can do about it
