### ISSUE TITLE
Short Link Page

### ISSUE THREAD

**Issue by jyxzhang** [ocf/ocfstatic#196]
Goal: Implement a page with a table of short links ( https://github.com/ocf/ocfweb/issues/485 and https://github.com/ocf/projects/issues/64 ).
I'm just going to yoink @Strellic 's code https://gist.github.com/strellic/8e55f273d8e8d9873d5a49fce1866546 and try to port it to Vue I guess.

**Comment by jyxzhang** [comment]
I think I'll put it at https://new.ocf.berkeley.edu/shorturls , does anyone have any suggestions on where this could be linked to? It would probably fit well under documentation, but from what I can see, documentation is a bunch of markdown files displayed on the website, so I'm not sure how to run scripts there.

**Comment by bentref** [comment]
This is a good idea!

If it's the `/shorturls` url then that is separate from documentation and it's no problem to add a link to that shorturls page from documentation. If you want it to actually be rendered as part of the documentation, with a `/docs/shorturls` url, that could run into the challenge you mentioned.
