### ISSUE TITLE
Complete Officers Page

### ISSUE THREAD

**Issue by jyxzhang** [ocf/ocfstatic#198]
The officer's page still needs some place for the past officers. It could be a separate page, or could be like a  dropdown at the bottom of the officer page. Also, all the officers are hardcoded right in the code. We should probably read the information from a file. On the old website, the contents are read [from here](https://github.com/ocf/ocfweb/blob/master/ocfweb/docs/views/officers.py), but I feel like since we aren't using Python and Django anymore, we should probably move to a different type of storage. The images for the officers will also need some file/folder setup.

**Comment by BernardZhao** [comment]
The images can be stored where the other images are stored and the contents can also be hardcoded, since it also is in existing ocfweb.

**Comment by bentref** [comment]
Closed by above PR ^
