### ISSUE TITLE
Navigation bar doesn't work till after reload

### ISSUE THREAD

**Issue by bentref** [ocf/ocfstatic#210]
Not sure when this happened--I don't remember it being an issue a while ago--but attempting to navigate to different pages doesn't work. The address bar changes but the view does not. 

Not an issue when running locally.

**Comment by ethanwu10** [comment]
Isolated this to an HTML comment in a Vue template:
https://github.com/ocf/ocfstatic/blob/242a809cc269fdf816f5e49359f341eb05c878fe/src/pages/Index.vue#L92

Removing it fixes the (silent) hydration crash on the index page. Making a PR in a moment...

Relevant issues: gridsome/gridsome#165 gridsome/gridsome#650
