### ISSUE TITLE
Update info about meetings on homepage

### ISSUE THREAD

**Issue by bentref** [ocf/ocfstatic#244]
Currently the staff meeting info on the homepage says the wrong date, and it doesn't say that the meetings are actually in person at the lab. This would be a good first issue for someone to change this!

**Comment by bentref** [comment]
Ooh, good catch! I'll fix that on my updated about page I'll be pushing soon--but moving forward @ben9583 suggested using a centralized way for keeping track of meeting times so that might be something to look into

**Comment by ben9583** [comment]
Yea I was taking a look at that earlier, I'd be happy to see what I can do there
