### ISSUE TITLE
Fetch meeting times from /ocf/etc

### ISSUE THREAD

**Issue by bentref** [ocf/ocfstatic#263]
@ben9583 has added [schema](https://github.com/ocf/etc/blob/master/schemas/meeting_hours.schema.json) and [YAML data](https://github.com/ocf/etc/blob/master/configs/meeting_hours.yaml) to centralize meeting hours. We have to actually implement this everywhere that we currently have hardcoded meeting dates.

This entails figuring out how to read from the YAML and then copying and pasting that to a few places.

**This is linked to #125 (fetching staff hours) since it's the same YAML files**

**Comment by bentref** [comment]
Yes it would appear that ocf/api is the API Bernard created to be used for this website, and it is possible to add routes to it for anything from ocflib. Maybe should coordinate on creating ocflib changes and ocf/api routes

**Comment by Kalissaac** [comment]
API endpoints exist here: https://api.ocf.berkeley.edu/docs#/meetings/get_meetings_list_meetings_list_get
