### ISSUE TITLE
Point API requests to localhost:8000 during development

### ISSUE THREAD

**Issue by bentref** [ocf/ocfstatic#268]
Goal: develop a way inside ocfstatic to automatically point [ocf/api](https://github.com/ocf/api) requests to localhost:8000 when in development and then point it to <https://api.ocf.berkeley.edu> when in production. I think requiring developers to manually override the url when they want to test an endpoint on a page adds an extra obstacle that needs be dealt with.

**Comment by Kalissaac** [comment]
We now have a `.env` file where you can manually override the API host, which mostly solves the issue
