### ISSUE TITLE
Use React

### ISSUE THREAD

**Issue by RonitNath** [ocf/ocfstatic#271]
We're using vue. Shall we use react instead?

Open for comments.

**Comment by nikhiljha** [comment]
I think Ethan pretty much said it all, although also of note is the fact that more people are familiar with React both within the OCF and probably in Berkeley in general. I'm a little sad that we will never get svelte ocfweb but I think it's worth it for maintainability and ecosystem support.

**Comment by ethanwu10** [comment]
Just wanted to add we've hit more problems with Gridsome already: Node 17 broke webpack's hashing function, and a fix landed in webpack 5, however webpack maintainers have stated that [it's not getting fixed for webpack 4](https://github.com/webpack/webpack/issues/14532#issuecomment-947513562). Meanwhile, [a pull for webpack 5 in Gridsome](https://github.com/gridsome/gridsome/pull/1523) has already been merged, however the last Gridsome *release* was a year ago (!!), so it has never been published.

...and of course more hydration problems have cropped up...

**Comment by RonitNath** [comment]
How much would break if we removed Gridsome?

**Comment by Kalissaac** [comment]
> How much would break if we removed Gridsome?

The only Gridsome-specific feature that I know of is the docs, since that uses Gridsome's data ingestion and then a search component.

**Comment by RonitNath** [comment]
https://github.com/ocf/ocfstatic/issues/279

**Comment by Kalissaac** [comment]
Completed (partially) in #325
