### ISSUE TITLE
Decide what to do with all those add to staff PRs

### ISSUE THREAD

**Issue by bentref** [ocf/ocfstatic#278]
These PRs look pretty unruly! They will probably still work (although the logic of displaying staff has been changed) so they could be cleaned up and redone or merged as is. But there are no photos!

**Comment by Kalissaac** [comment]
Maybe we can pull gravatars?

I think trying to coordinate getting photos from every person who is listed on the page would be... a lot

**Comment by Kalissaac** [comment]
Or we find something else to put in place of the photos, maybe some kind of auto generated avatar

**Comment by bentref** [comment]
> Maybe we can pull gravatars?

great idea! I'm not familiar with how gravatars work or how may people actually have them though

> Or we find something else to put in place of the photos, maybe some kind of auto generated avatar

Yeah this would be the next best, but if this is the case we'd want to make the photos a good deal smaller

**Comment by Kalissaac** [comment]
> I'm not familiar with how gravatars work

You can just take the md5 hash of the user's email and then append it to the Gravatar API URL at `https://www.gravatar.com/avatar/<EMAIL_HASH>`
e.g. https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50

> how may people actually have them though

Yeah that's true, it came to mind because that's what we're already using for the avatars of logged in users. I don't think many people have gravatars, especially ones linked to their ocf or berkeley email address.

**Comment by kpengboy** [comment]
Don't we use Gravatars on the staff hours page? Many alumni probably still have those linked to their OCF emails too.

**Comment by bentref** [comment]
> You can just take the md5 hash of the user's email

Ah, that's cool! The current PRs don't include people's emails (only handle) so we'd have to add those to the data, but I think we have everyone's emails somewhere from being on staff

**Comment by Kalissaac** [comment]
Maybe we can just do `<handle>@ocf.berkeley.edu`?

**Comment by bentref** [comment]
We could, but what percentage of people have their gravatar linked to that address?

**Comment by bentref** [comment]
If we encourage people to update their gravatars (like talk about it in a staff meeting), we could get much better coverage probably

**Comment by bentref** [comment]
Issue is already added for photos, #262

**Comment by Kalissaac** [comment]
Since our rewrite in React no longer has a staff page, I'll close this for now since we'll want to find a new solution with the current site
