### ISSUE TITLE
Refactor Gridsome Out

### ISSUE THREAD

**Issue by RonitNath** [ocf/ocfstatic#279]
Gridsome isn't that great and we're unsure about its level of future long term support.

Since it's apparently mainly being used for the docs and search features, we should find replacements for both these functionalities and implement those instead.

**Comment by rhsf** [comment]
Somewhat relevant to #271, but...

If we're only looking to swap Gridsome out and not rewrite everything in React, then I think https://nuxtjs.org could be a good drop-in replacement.

We can use SSG mode to statically generate the docs (a la Jekyll), or SSR mode and use middleware to connect to other OCF APIs.

Fancy websites that use Nuxt: https://nuxtjs.org/showcases

**Comment by Kalissaac** [comment]
Completed in #271
