### ISSUE TITLE
Extract docs to their own repo

### ISSUE THREAD

**Issue by Kalissaac** [ocf/ocfstatic#295]
The documentation is currently duplicated across ocfweb and ocfstatic. This means that the content of them has diverged between the two websites, with some people making PRs to add content to docs on ocfweb and some PRs to ocfstatic. I've already started a repo at https://github.com/Kalissaac/ocfdocs with the docs content and I think I've been able to merge everything together so far. On the branch `kian/extract-docs` I've done the work of using a git submodule to point the docs folder to that repo which will allow us to update docs in one place and have it take effect everywhere on the site.

**Comment by kpengboy** [comment]
Can we migrate the history of the docs as well? We did this last time when we migrated from the `wiki-old` repository to the `ocfweb` repository.

**Comment by Kalissaac** [comment]
Definitely, I didn't realize git had this feature!

**Comment by kpengboy** [comment]
Right, you might want to check out git-filter-repo for extracting just the changes to documentation (as opposed to other ocfweb changes) and perhaps rewriting paths as desirable.

**Comment by Kalissaac** [comment]
I used `git subtree split` and I think it turned out well? This is the new temporary docs repo: https://github.com/Kalissaac/newocfdocs
Still need to convert the links to Markdown links and a couple other fixes.

**Comment by Kalissaac** [comment]
Yeah rewriting the paths is going to be another issue, since ocfstatic moved a bunch of docs into the internal/ folder

**Comment by Kalissaac** [comment]
Need to incorporate #307
