### ISSUE TITLE
Menu bar is not aria compliant

### ISSUE THREAD

**Issue by lawrencecchen** [ocf/ocfstatic#315]
It should be possible (keyboard) tab to all dropdown items. Usually, this is handled by an external component/aria library (eg. react-aria, headlessui, radix-ui). Not sure what's the best for Vue, but [headlessui](https://headlessui.com/vue/menu) looks reasonable. Thoughts?

https://user-images.githubusercontent.com/54008264/191653000-45d68301-5779-44c5-8a49-a14ea3daa32c.mov

**Comment by skrider** [comment]
Looks like Buefy's [Menu Dropdowns](https://buefy.org/documentation/navbar) are not aria compliant. Their regular [dropdowns](https://buefy.org/documentation/dropdown), interestingly, are.

**Comment by Kalissaac** [comment]
We use Chakra UI in our new React rewrite which provides accessible components, and I just tested and keyboard navigation seems to be working properly now. Please reopen if the issue persists.
